### ISSUE TITLE
Confused about vert_parameters in the feature YAML file

### ISSUE THREAD

**Issue by bertjiazheng** [deep-geometry/abc-dataset#10]
Hi, 

Recently, I use the feature YAML file to generate the parametric curves. After generating some cases, I found some errors in variable `vert_parameters`. 

Here is the example (_00000050_80d90bfdd2e74e709956122a_features_000_) provided on the homepage:
```yaml
- location: [23.1470415124478, -1.5875, -1.1967223111172498]
  radius: 3.175
  sharp: true
  type: Circle
  vert_indices: [7, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 8]
  vert_parameters: [2.9976021664879227e-15, 274.39539218140305, 548.7907843628058,
    823.1861765442086, 1097.581568725611, 1371.9769609070152, 1646.3723530884192,
    1920.7677452698233, 2195.1631374512267, 2469.558529632629, 2743.9539218140308,
    3018.3493139954317, 3.2927447061768333]
  x_axis: [0.9885982612261511, 0.0, 0.15057714933093502]
  y_axis: [0.15057714933093502, 0.0, -0.9885982612261511]
  z_axis: [-0.0, 1.0, 0.0]
```

I compare the generated points by _vert_parameters_ with mesh vertices, and found vert_parameters[1:-1] should be divided by 1000. 

Looking forward to your reply. 

Best,
Jia
