### ISSUE TITLE
FeatureScript seems not to be the same thing as OnShape FeatureScript

### ISSUE THREAD

**Issue by Somedaywilldo** [deep-geometry/abc-dataset#4]
Dear Authors,

Thank you for providing the FeatureScript, I've examine the content in it, I can really tell it contains information about constrains or manipulations in OnShape. However, I got these questions:

1. In OnShape, feature script should refer to a programming language to write custom features, it should looks like this:
```
var myLine is Line = evEdgeTangentLine(context, {
    "edge" : definition.edge1,
    "parameter" : 0.5
});
var myPoint is Vector = myLine.origin + myLine.direction * 2.5 * inch;

debug(context, myLine);
debug(context, myPoint);
```
However, in your data, the feature script looks like this:

```
defaultFeatures:
- message:
    featureId: Origin
    featureType: origin
    hasUserCode: false
    name: Origin
    namespace: ''
    nodeId: MWbE22OwgQmBfS22C
    parameters: []
    returnAfterSubfeatures: false
    subFeatures: []
    suppressed: false
    suppressionState:
      type: 0
  type: 134
  typeName: BTMFeature
```

So could you please give me some explanation of: 

1. How did you get these kind of FeatureScript? 
2. Is it relevant to the "FeatureScript" on OnShape? 
3. Is there anyway to load this script on OnShape? How can we make use of it?

Thank you!
